---
- name: Update  apt cache and install dependencies on Ubuntu
  apt:
    update_cache: yes
    name: build-essential
    state: present
  when: ansible_facts['os_family'] == "Debian"


- name: Update  apt cache and install dependencies on CentOS
  yum:
    name: "@Development Tools"
    state: present 
  when: ansible_facts['os_family'] == "RedHat"



